### ISSUE TITLE
Use Glitch animation to each section title and type animation to about section content

### ISSUE THREAD

**Issue by Saifkhan-rkp** [Saifkhan-rkp/portfolio#11]
Add `glitch` class to each section title. Uncomment the code for type animation from `index.js` make some changes according to code for content of about section(about paragraph)

**Comment by keshav-09** [comment]
Hi @Saifkhan-rkp ,

I would like to work on this task.
Could you please explain the first line (add the class to the section title) so that I can have a clearer understanding of the task?

**Comment by Saifkhan-rkp** [comment]
yes @keshav-09 .. class inside the html tag like example below.
```html
<h2 class="glitch" data-slice="20" >title</h2>
```

**Comment by keshav-09** [comment]
Okay @Saifkhan-rkp , 
Thank you for your help.
I will do the necessary changes and let you know.
