### ISSUE TITLE
Design HTML page according to theme  

### ISSUE THREAD

**Issue by Saifkhan-rkp** [Saifkhan-rkp/portfolio#3]
Add each section for nav item(except github) with their title in `index.html` file 

1. divide each section in two part (except hero), into `title-container` and `content-container`
2. divide each section into 30:70 ratio
3. title should be in center of section container 
4. modify `style.css` file accordingly

**Comment by shubham-ghaturle01** [comment]
Hi  @Saifkhan-rkp ,

I’d like to propose the following updates for the portfolio website:

Divide each section (except Hero) into two parts:
Title-container (centered title).
Content-container (section content).
Adjust the layout to a 30:70 ratio (Title on the left, content on the right).
Please let me know if I have your permission to implement these changes.

Thank you!
Shubham Ghaturle

**Comment by Saifkhan-rkp** [comment]
@Shubhuscode yes sure Shubham i would like to. please make sure you do this in single commit please follow the readme file for contribution. please let me know any support required

**Comment by shubham-ghaturle01** [comment]
@Saifkhan-rkp, the code has already been merged #15 , but the issue is still open. Please close it.

**Comment by Saifkhan-rkp** [comment]
Thanks @Shubhuscode.
