### ISSUE TITLE
About section to be added

### ISSUE THREAD

**Issue by Saifkhan-rkp** [Saifkhan-rkp/portfolio#6]
About section hasn't developed yet.
Develop about section, use dummy for initial make sure it matches the theme refer the following:

1. Should follow alternate Section color (first `#000`  and followed by  `#1a1e23`)
2. Title(About) of section should be on left side and content (paragraph) on right side
3. Font for content should be `"digital geometric"`
4. content should be in card same configuration as project card 
5. All of the above task should be in one commit

**Comment by MuktaTiwari** [comment]
Hii @Saifkhan-rkp 
I would like to handle these things, so can I do it for you ?
and can you please provide me the information about what comes under the paragraph in the About section instead of dummy details?

**Comment by Saifkhan-rkp** [comment]
Hi.. @MuktaTiwari  thanks for solving this issue. Sure, i am providing you my resume drive link for your reference. feel free for ask anything regarding this issue. [drive resume link](https://drive.google.com/file/d/1TlGJE5YVW-ck9vHYI0ZQzEWIKpytYvtq/view?usp=drive_link)

**Comment by MuktaTiwari** [comment]
can you please give me the of your Drive?
I have requested for access.

**Comment by Saifkhan-rkp** [comment]
yes I did, check the link again.

**Comment by Saifkhan-rkp** [comment]
This issue has been completed by @MuktaTiwari , thank you.
