### ISSUE TITLE
Contact section to be added to the portfolio

### ISSUE THREAD

**Issue by Saifkhan-rkp** [Saifkhan-rkp/portfolio#7]
To develop contact section in following manner:

1. Follow the theme, alternate section colors (`#000` followed by `#1a1e23`) 
2. Left side to the title (Contact) and right side to the content(Contact links)
3. All social media contact should be added (Instagram, Telegram, WhatsApp, e-Mail) use dummy for instance or contact 
4. Use icons if needed, if not cdn links then add to `assets/icons` folder 
5. All of the above tasks should be in one commit

**Comment by kambleaishwarya** [comment]
Hi Saif, I would like to take up this issue. If you permit, please comment Accordingly, I will start working on it.

**Comment by Saifkhan-rkp** [comment]
hello.. @kambleaishwarya yes please. ask me if any further details needed on this issue. thanks.

**Comment by kambleaishwarya** [comment]
hello saif,can we use swiper pagination with the help of javascript to display all the contacts like whatsapp, insta, telegram etc.?

**Comment by Saifkhan-rkp** [comment]
Yes @kambleaishwarya , you can. make sure to code in js file instead of html script tag.

**Comment by Saifkhan-rkp** [comment]
One more thing can adjust the height of the contact section to 60vh. please @kambleaishwarya make this change as well.

**Comment by kambleaishwarya** [comment]
> Yes @kambleaishwarya , you can. make sure to code in js file instead of html script tag.

yes sure , thnaku for your guidance

**Comment by kambleaishwarya** [comment]
> One more thing can adjust the height of the contact section to 60vh. please @kambleaishwarya make this change as well.

yes sure i will do it

**Comment by kambleaishwarya** [comment]
- do you want to keep font-family same as existing?

**Comment by Saifkhan-rkp** [comment]
> * do you want to keep font-family same as existing?

Yes it will be the same.

**Comment by kambleaishwarya** [comment]
okay

**Comment by kambleaishwarya** [comment]
in  the js file i have kept commented code as it is

**Comment by kambleaishwarya** [comment]
Hey Saif, good morning! I have raised a PR. Please check it out and let me know if any further changes are required in the code.

**Comment by Saifkhan-rkp** [comment]
> Hey Saif, good morning! I have raised a PR. Please check it out and let me know if any further changes are required in the code.

Hii @kambleaishwarya , good morning. i have closed the PR, the commit is not meet as expected refer comment on #19 an d read the [doc](https://github.com/Saifkhan-rkp/portfolio#contributing). and do changes accordingly.
