### ISSUE TITLE
fix iframe issue and provide valid project details as content in Projects section

### ISSUE THREAD

**Issue by Saifkhan-rkp** [Saifkhan-rkp/portfolio#8]
Following tasks to be completed in this issue: 

1. About each project in few lines(refer GitHub repository of individual) to add  
2. Font of project details should be `"digital geometric"`
3. Project link have mention in each card of project, if any 
 example: package link of npmjs and vercel link of another project tobe added above github link
4. Fix iframe issue remove if needed and add Screen Shots of each 
5. each of the above task have different commit if needed else should in one

**Comment by arshad-khan1** [comment]
Hi @Saifkhan-rkp,
I can help you with fixing this issue.
Please let me know so that I can start working on it.

Thanks,
Arshad Khan

**Comment by Saifkhan-rkp** [comment]
@arshad-khan1 sure you can work on.

**Comment by arshad-khan1** [comment]
@Saifkhan-rkp, Can you please provide me with the screenshots that has been mention in point 4.

**Comment by Saifkhan-rkp** [comment]
@arshad-khan1 okay, I'm attaching a link of drive where you can find screenshots. an d for project details you will find on my GitHub. 
[SS drive link](https://drive.google.com/drive/folders/1jrko1g0HG_6K2PK-DTPSJj1170uMDFEd?usp=sharing)

#### project links
* [backforge](https://github.com/Saifkhan-rkp/backforge)
* [vizfaculty](https://github.com/Saifkhan-rkp/VizFaculty-FrontEnd)
* [image forgery](https://github.com/Saifkhan-rkp/forgery_detection)

**Comment by arshad-khan1** [comment]
@Saifkhan-rkp, Created PR #23 please check
